# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test executor inputs

on:
  workflow_dispatch:
  pull_request:
    branches: [main, develop, develop-feijoa]

jobs:
  build:
    runs-on: [self-hosted, linux, X64, hc]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: setup zkevm-rom
        run: |
          npm i
          npm run build
          npm run test:build:gasLimit:v1
          npm run test:build:gasLimit:v2
          npm run test:build:gasLimit:v3
      - name: run counters tests
        run: |
          npm run test:counters
      - name: run zkasm tests
        run: |
          npm run test:zkasm
      - name: Generate tests
        run: |
          npm run test:gen
      - name: Run tests
        run: |
          export NUM_CPUS=31
          npm run test:start
          sh tools/parallel-testing/checker.sh